// Banco canônico de 53 estratégias (Metodologia v2).
// Títulos: transcrição de "Nyta_Etapa_Estrategias_v3" §3. Passo a passo (10 tarefas cada):
// transcrição de "Nyta_Etapa_Plano_de_Acao_v1" §4. Tudo determinístico, sem LLM.
//
// `id` é a chave canônica usada pelas Matrizes A/B/C (./matrices.ts), pela matriz de priorização
// (./priorityMatrix.ts) e por este passo a passo. A numeração é a original, não-sequencial
// (os removidos 7/16/21/27/28/45/56/57/N4/N5 não são reaproveitados).
//
// `order` (1–27) é a seção 3.x do banco — define a ordem de apresentação ao artista.
// Placeholders no título: `[nome]` (substituído pelo nome artístico na personalização).

export interface BankStrategy {
  id: string;
  order: number;
  category: string;
  title: string;
  tasks: string[];
}

export const STRATEGY_BANK: BankStrategy[] = [
  // ── 3.1 Lançamentos fonográficos ─────────────────────────────────────────────────────────────
  {
    id: '1',
    order: 1,
    category: 'Lançamentos fonográficos',
    title: 'Criar uma programação estruturada de lançamentos fonográficos em parceria com distribuidora com atendimento, incluindo feats / participações especiais e estratégia de pitching para playlists editoriais',
    tasks: [
      'Listar todas as músicas prontas e em produção',
      'Definir o que vai ser lançado nos próximos 12 meses (singles, EP ou álbum)',
      'Montar um calendário com a data de cada lançamento',
      'Pesquisar 5 distribuidoras com atendimento adequadas ao seu nicho',
      'Pedir proposta comercial para 3 distribuidoras',
      'Escolher 1 distribuidora e fechar o contrato',
      'Listar artistas para feats e escolher 3 para convidar',
      'Fazer os convites de feat com antecedência',
      'Preparar o material de cada lançamento (capa, áudio, texto de pitching)',
      'Enviar o pitching para a distribuidora 4 semanas antes de cada lançamento',
    ],
  },
  {
    id: '2',
    order: 1,
    category: 'Lançamentos fonográficos',
    title: 'Avaliar parceria com selo ou adiantamento com a distribuidora',
    tasks: [
      'Listar selos e distribuidoras do seu nicho',
      'Pesquisar quais oferecem adiantamento',
      'Levantar o que cada um pede em troca (percentual, exclusividade, prazo)',
      'Organizar seus números para apresentar (streams, público, agenda)',
      'Entrar em contato com 3 selos ou distribuidoras',
      'Apresentar seu projeto e seus números',
      'Receber e comparar as propostas',
      'Avaliar prós e contras de cada uma (com apoio jurídico, se possível)',
      'Negociar os termos da escolhida',
      'Fechar o contrato',
    ],
  },

  // ── 3.2 Distribuição, edição e direitos ──────────────────────────────────────────────────────
  {
    id: '3',
    order: 2,
    category: 'Distribuição, edição e direitos',
    title: 'Constituir editora própria (migrar empresa para LTDA com CNAE de edição) e fazer contrato de administração com editora major',
    tasks: [
      'Entender como funciona uma editora musical e o que ela arrecada',
      'Consultar um contador sobre incluir a atividade de edição na empresa',
      'Migrar a empresa para LTDA com CNAE de edição',
      'Listar todas as suas obras registradas',
      'Filiar a editora a uma associação de arrecadação',
      'Pesquisar editoras major que fazem contrato de administração',
      'Entrar em contato com 2 ou 3 editoras major',
      'Comparar as propostas de administração',
      'Negociar os termos',
      'Assinar o contrato de administração',
    ],
  },
  {
    id: '4',
    order: 2,
    category: 'Distribuição, edição e direitos',
    title: 'Prospectar oportunidades de sincronização (trilhas para filmes, séries, publicidade)',
    tasks: [
      'Entender o que é sincronização e que tipo de música tem demanda',
      'Organizar seu catálogo com as músicas disponíveis para sync',
      'Garantir que os direitos das obras estão registrados',
      'Preparar uma pasta com as músicas e informações para sync',
      'Listar produtoras, agências de publicidade e supervisores musicais',
      'Pesquisar plataformas e bibliotecas de sincronização',
      'Cadastrar as músicas nessas plataformas',
      'Entrar em contato apresentando o catálogo',
      'Responder aos briefings que aparecerem',
      'Registrar cada licenciamento fechado',
    ],
  },
  {
    id: '5',
    order: 2,
    category: 'Distribuição, edição e direitos',
    title: 'Registrar as obras e a marca',
    tasks: [
      'Listar todas as músicas que precisam ser registradas',
      'Escolher onde registrar as obras (Biblioteca Nacional, associação)',
      'Reunir letras e fonogramas de cada obra',
      'Fazer o registro de cada obra',
      'Guardar os comprovantes numa pasta',
      'Pesquisar se o nome artístico está disponível no INPI',
      'Reunir a documentação para registro de marca',
      'Dar entrada no pedido de registro de marca',
      'Acompanhar o andamento do pedido',
      'Guardar o comprovante e anotar a data de renovação',
    ],
  },

  // ── 3.3 Branding e identidade visual ─────────────────────────────────────────────────────────
  {
    id: '6',
    order: 3,
    category: 'Branding e identidade visual',
    title: 'Contratar consultoria de branding para definição do naming e da nova identidade visual',
    tasks: [
      'Pesquisar 5 profissionais ou consultorias de branding com experiência em música',
      'Ver o portfólio de cada um e marcar os 3 que mais combinam com você',
      'Pedir orçamento e prazo para os 3 selecionados',
      'Marcar uma conversa (call ou presencial) com os 2 mais promissores',
      'Escolher 1 e fechar o contrato',
      'Reunir e enviar suas referências visuais, músicas e textos',
      'Participar da reunião de imersão / briefing',
      'Receber a proposta de naming e identidade e dar seu retorno',
      'Aprovar a versão final (logo, paleta, tipografia)',
      'Receber o manual da marca e salvar numa pasta organizada',
    ],
  },

  // ── 3.4 Material promocional ─────────────────────────────────────────────────────────────────
  {
    id: '8',
    order: 4,
    category: 'Material promocional',
    title: 'Produzir novo material promocional baseado no branding (fotos, release, bio, PDF de apresentação, vídeo de venda do show)',
    tasks: [
      'Listar tudo que precisa de material novo (fotos, release, bio, PDF, vídeo)',
      'Pesquisar 3 fotógrafos alinhados à nova identidade',
      'Fechar o fotógrafo e marcar a data do ensaio',
      'Fazer o ensaio de fotos',
      'Selecionar e tratar as melhores fotos',
      'Escrever a bio curta e a bio longa',
      'Escrever o release (avaliar aspas de jornalista ou personalidade)',
      'Montar o PDF de apresentação com fotos, bio e infos do show',
      'Editar o vídeo de venda do show',
      'Organizar todo o material numa pasta de fácil acesso para envio',
    ],
  },
  {
    id: '9',
    order: 4,
    category: 'Material promocional',
    title: 'Criar media kit criativo para envio a influenciadores e veículos nos lançamentos estratégicos',
    tasks: [
      'Definir o conceito do media kit (o que quer provocar)',
      'Reunir as melhores fotos, vídeos e números',
      'Escrever o texto curto de apresentação',
      'Definir o formato (PDF, vídeo, objeto físico criativo)',
      'Produzir o media kit',
      'Revisar e aprovar a versão final',
      'Listar os influenciadores e veículos que vão receber',
      'Personalizar o envio para cada um',
      'Enviar nos períodos de lançamento',
      'Acompanhar quem recebeu e respondeu',
    ],
  },

  // ── 3.5 Redes sociais e gestão digital ───────────────────────────────────────────────────────
  {
    id: '10',
    order: 5,
    category: 'Redes sociais e gestão digital',
    title: 'Contratar profissional para gestão estruturada das redes sociais, com definição de canais prioritários, editorias de conteúdo e tráfego pago nos lançamentos',
    tasks: [
      'Definir quais redes são prioritárias para o seu público',
      'Pesquisar 3 social medias ou profissionais de marketing digital',
      'Pedir proposta e ver trabalhos anteriores dos 3',
      'Escolher 1 e fechar o contrato',
      'Definir junto com o profissional as editorias de conteúdo',
      'Montar o cronograma de postagens do mês',
      'Reservar a verba mensal para tráfego pago',
      'Definir a estratégia de tráfego pago para os lançamentos',
      'Acompanhar as métricas no fim de cada mês',
      'Ajustar o que não estiver dando resultado',
    ],
  },
  {
    id: '11',
    order: 5,
    category: 'Redes sociais e gestão digital',
    title: 'Reenvelopar perfis com a nova identidade',
    tasks: [
      'Listar todos os perfis e canais ativos',
      'Reunir os elementos da nova identidade (logo, paleta, fotos)',
      'Atualizar foto de perfil e capa de cada rede',
      'Reescrever a bio de cada rede com o novo posicionamento',
      'Atualizar os destaques fixados',
      'Atualizar o link da bio (site ou agregador)',
      'Padronizar o visual dos próximos posts',
      'Revisar se todos os canais ficaram coerentes',
      'Publicar um post comunicando o novo momento',
      'Conferir se ficou tudo alinhado',
    ],
  },
  {
    id: '12',
    order: 5,
    category: 'Redes sociais e gestão digital',
    title: 'Trabalhar gestão de comunidade (super-fãs, WhatsApp, Telegram), incluindo modelos de remuneração recorrente (plano de assinatura, clube de apoiadores, "sustente seu artista")',
    tasks: [
      'Escolher onde criar a comunidade (WhatsApp, Telegram, plataforma de assinatura)',
      'Definir o que a comunidade vai receber de especial',
      'Definir se vai ter mensalidade e qual valor',
      'Configurar a plataforma escolhida',
      'Criar as regras e a mensagem de boas-vindas',
      'Convidar seus fãs mais próximos para entrar',
      'Divulgar a comunidade nas redes',
      'Criar um cronograma de conteúdo e encontros',
      'Manter a frequência de interação',
      'Acompanhar o crescimento e a retenção dos membros',
    ],
  },

  // ── 3.6 Canais próprios e CRM ────────────────────────────────────────────────────────────────
  {
    id: '13',
    order: 6,
    category: 'Canais próprios e CRM',
    title: 'Criar site com área de captação de leads (CRM para gestão e nutrição da base)',
    tasks: [
      'Registrar o domínio do site',
      'Contratar a hospedagem',
      'Definir as seções do site (bio, agenda, contato, cadastro)',
      'Desenvolver o site (por conta própria ou com profissional)',
      'Criar a área de cadastro de e-mails',
      'Escolher a plataforma de e-mail marketing / CRM',
      'Conectar o cadastro do site à plataforma de e-mail',
      'Criar uma oferta de conteúdo em troca do cadastro',
      'Publicar o site no ar',
      'Enviar o primeiro e-mail para a base cadastrada',
    ],
  },
  {
    id: '14',
    order: 6,
    category: 'Canais próprios e CRM',
    title: 'Mapear e organizar a base de contatos por tipo (jornalistas, contratantes, músicos, fãs), segmentar e ativar fluxo de comunicação estratégico e constante',
    tasks: [
      'Reunir todos os contatos que você já tem (celular, e-mail, redes)',
      'Criar uma planilha única de contatos',
      'Classificar cada contato por tipo (jornalista, contratante, músico, fã)',
      'Identificar os contatos mais estratégicos',
      'Listar os contatos de interesse que você ainda não tem',
      'Buscar como chegar nesses contatos novos',
      'Definir um fluxo de comunicação para cada tipo (o quê e com que frequência)',
      'Criar listas de transmissão ou grupos segmentados',
      'Enviar a primeira comunicação para cada grupo',
      'Manter o contato regular conforme o fluxo definido',
    ],
  },

  // ── 3.7 Imprensa e mídia ─────────────────────────────────────────────────────────────────────
  {
    id: '15',
    order: 7,
    category: 'Imprensa e mídia',
    title: 'Trabalhar imprensa e mídia: contratar assessoria para os períodos de lançamento (incluindo podcasts e YouTube) ou mapear veículos, jornalistas e influencers de interesse para contato direto',
    tasks: [
      'Decidir se vai contratar assessoria ou fazer por conta própria',
      'Se for contratar: pesquisar 3 assessorias com atuação no seu nicho',
      'Pedir cases e orçamento das 3',
      'Escolher 1 e fechar para o período do lançamento',
      'Se for por conta própria: listar 15 veículos e jornalistas de interesse',
      'Levantar o contato de cada um',
      'Preparar o release e o kit de imprensa do lançamento',
      'Enviar o material para os veículos com antecedência',
      'Fazer follow-up com quem não respondeu',
      'Registrar a cobertura num documento de clipping',
    ],
  },
  {
    id: '17',
    order: 7,
    category: 'Imprensa e mídia',
    title: 'Prospectar participações em podcasts e canais do YouTube',
    tasks: [
      'Listar podcasts e canais do YouTube alinhados ao seu público',
      'Ver quais já receberam artistas parecidos com você',
      'Levantar o contato de cada um',
      'Preparar um material curto de apresentação (pitch)',
      'Escolher um gancho (lançamento, história, pauta)',
      'Entrar em contato propondo a participação',
      'Fazer follow-up com quem não respondeu',
      'Agendar as participações confirmadas',
      'Participar e divulgar nas suas redes',
      'Registrar os contatos para futuras participações',
    ],
  },

  // ── 3.8 Rádio ────────────────────────────────────────────────────────────────────────────────
  {
    id: '18',
    order: 8,
    category: 'Rádio',
    title: 'Trabalhar rádio: contratar divulgador no nicho ou mapear rádios estratégicas para propor parcerias',
    tasks: [
      'Decidir se vai contratar divulgador ou fazer por conta própria',
      'Se contratar: pesquisar divulgadores de rádio do seu nicho',
      'Pedir orçamento e resultados anteriores',
      'Fechar com um divulgador',
      'Se for por conta própria: mapear rádios estratégicas do segmento',
      'Levantar o contato das rádios e programadores',
      'Preparar a música e o material de envio',
      'Enviar a música propondo execução ou parceria',
      'Fazer follow-up',
      'Acompanhar em quais rádios a música entrou',
    ],
  },

  // ── 3.9 YouTube e podcast próprio ────────────────────────────────────────────────────────────
  {
    id: '19',
    order: 9,
    category: 'YouTube e podcast próprio',
    title: 'Criar programação estruturada de conteúdo para o YouTube',
    tasks: [
      'Definir o objetivo do canal (o que quer que o público encontre)',
      'Definir os tipos de conteúdo (clipes, bastidores, ao vivo)',
      'Olhar o que o seu acervo já permite publicar',
      'Montar um cronograma de publicação',
      'Padronizar capas e títulos',
      'Produzir os primeiros conteúdos',
      'Otimizar título, descrição e tags de cada vídeo',
      'Publicar conforme o cronograma',
      'Divulgar os vídeos nas outras redes',
      'Acompanhar as métricas e ajustar',
    ],
  },
  {
    id: '20',
    order: 9,
    category: 'YouTube e podcast próprio',
    title: 'Lançar podcast (ou videocast) próprio',
    tasks: [
      'Definir o tema e o formato do podcast',
      'Definir a frequência (semanal, quinzenal)',
      'Listar os primeiros convidados ou pautas',
      'Definir o equipamento e o local de gravação',
      'Criar a identidade do podcast (nome, capa)',
      'Gravar o episódio piloto',
      'Escolher onde hospedar (Spotify, YouTube)',
      'Editar o primeiro episódio',
      'Publicar e divulgar',
      'Manter a frequência de publicação',
    ],
  },

  // ── 3.10 Network ─────────────────────────────────────────────────────────────────────────────
  {
    id: '22',
    order: 10,
    category: 'Network',
    title: 'Participar de eventos, congressos e showcases do mercado da música presencialmente e interagir digitalmente com a cena',
    tasks: [
      'Listar os eventos e congressos de música do ano',
      'Marcar as datas no calendário',
      'Escolher os mais estratégicos para participar',
      'Preparar seu elevator pitch (apresentação de 30 segundos)',
      'Garantir inscrição ou credenciamento',
      'Levantar quem vai estar lá que te interessa conhecer',
      'Participar e fazer contatos presenciais',
      'Trocar contato com as pessoas que conheceu',
      'Fazer follow-up depois do evento',
      'Interagir digitalmente com a cena entre os eventos',
    ],
  },

  // ── 3.11 Show e palco ────────────────────────────────────────────────────────────────────────
  {
    id: '23',
    order: 11,
    category: 'Show e palco',
    title: 'Finalizar/montar o show e fazer show de lançamento com registro audiovisual para geração de material de venda',
    tasks: [
      'Fechar o repertório do show',
      'Definir o roteiro e a ordem das músicas',
      'Marcar os ensaios com a banda',
      'Ensaiar até o show estar pronto para o palco',
      'Escolher a data e o espaço do show de lançamento',
      'Contratar a equipe técnica (som, luz)',
      'Contratar quem vai filmar e fotografar',
      'Divulgar o show de lançamento',
      'Realizar o show e gravar em áudio e vídeo',
      'Editar trechos para o vídeo de venda e conteúdo de redes',
    ],
  },
  {
    id: '24',
    order: 11,
    category: 'Show e palco',
    title: 'Trabalhar presença de palco com profissional, incluindo marcações de roteiro',
    tasks: [
      'Identificar o que você quer melhorar no palco',
      'Pesquisar profissionais (preparador, diretor de show, coreógrafo)',
      'Ver trabalhos anteriores e pedir orçamento',
      'Fechar com um profissional',
      'Marcar as sessões de trabalho',
      'Definir as marcações de roteiro do show',
      'Ensaiar a performance com as marcações',
      'Gravar um ensaio para avaliar',
      'Ajustar os pontos fracos',
      'Aplicar no próximo show',
    ],
  },
  {
    id: '25',
    order: 11,
    category: 'Show e palco',
    title: 'Criar diferentes formatos de show (solo, banda, acústico, versão baixo custo) adequados a cada tipo de contratante',
    tasks: [
      'Listar os formatos possíveis (solo, banda, acústico, reduzido)',
      'Definir para que tipo de contratante serve cada formato',
      'Montar o repertório de cada formato',
      'Definir a ficha técnica de cada formato',
      'Definir o preço de cada formato',
      'Ensaiar cada formato',
      'Registrar cada formato em vídeo',
      'Montar material de venda para cada formato',
      'Incluir os formatos no material de prospecção',
      'Oferecer o formato certo para cada contratante',
    ],
  },

  // ── 3.12 Gestão comercial / Venda de shows ───────────────────────────────────────────────────
  {
    id: '26',
    order: 12,
    category: 'Gestão comercial / Venda de shows',
    title: 'Estruturar a venda de shows: identificar o tipo de cliente ideal, preparar material de venda específico, ativar prospecção estruturada com metas e acompanhamento, e criar fluxo de atendimento (pré e pós-venda), seja por conta própria ou via parceria com booker / agente comercial',
    tasks: [
      'Definir o tipo de cliente ideal para o seu show',
      'Listar os tipos de contratante (casas, prefeituras, corporativo, particular)',
      'Preparar um material de venda específico para cada tipo',
      'Definir o preço do show para cada tipo de contratante',
      'Decidir se a prospecção será própria ou via booker / assistente',
      'Se for via booker: pesquisar e fechar parceria com um',
      'Montar uma planilha de leads (contratantes para prospectar)',
      'Definir a meta de contatos por semana',
      'Ativar a prospecção e registrar cada contato na planilha',
      'Criar um roteiro de atendimento (o que responder, como fechar, pós-venda)',
    ],
  },

  // ── 3.13 Prospecção por tipo de contratante ──────────────────────────────────────────────────
  {
    id: '29',
    order: 13,
    category: 'Prospecção por tipo de contratante',
    title: 'Prospectar shows em órgãos públicos, prefeituras e SESC',
    tasks: [
      'Listar prefeituras, SESC, SESI e órgãos da sua região',
      'Entender como cada um contrata (edital, chamamento, convite)',
      'Levantar os contatos das secretarias de cultura',
      'Preparar material de venda adequado ao setor público',
      'Mapear editais e chamamentos abertos',
      'Cadastrar-se nos sistemas necessários',
      'Enviar proposta e material para os contatos',
      'Inscrever-se nos editais correspondentes',
      'Fazer follow-up',
      'Registrar os contatos e resultados numa planilha',
    ],
  },
  {
    id: '30',
    order: 13,
    category: 'Prospecção por tipo de contratante',
    title: 'Prospectar shows corporativos',
    tasks: [
      'Listar tipos de empresas e eventos corporativos do seu perfil',
      'Mapear agências de eventos corporativos',
      'Preparar material de venda voltado para o corporativo',
      'Definir o preço para esse mercado',
      'Levantar contatos de RH, marketing e agências',
      'Entrar em contato apresentando o show',
      'Enviar o material de venda',
      'Fazer follow-up',
      'Negociar e fechar',
      'Registrar os contatos numa planilha',
    ],
  },
  {
    id: '31',
    order: 13,
    category: 'Prospecção por tipo de contratante',
    title: 'Prospectar shows particulares (casamentos, eventos privados)',
    tasks: [
      'Definir o produto para eventos particulares (casamento, festa)',
      'Preparar material de venda para esse público',
      'Definir o preço para cada tipo de evento',
      'Mapear cerimonialistas e produtores de eventos',
      'Levantar os contatos',
      'Entrar em contato apresentando o serviço',
      'Enviar material e repertório',
      'Fazer follow-up',
      'Negociar e fechar',
      'Pedir indicação para clientes satisfeitos',
    ],
  },
  {
    id: '32',
    order: 13,
    category: 'Prospecção por tipo de contratante',
    title: 'Prospectar shows em casas de show e teatros (incluindo casas nichadas quando aplicável)',
    tasks: [
      'Listar casas de show e teatros do seu perfil e região',
      'Entender o modelo de cada um (cachê, bilheteria, parceria)',
      'Preparar material de venda com vídeo do show',
      'Levantar os contatos dos programadores',
      'Entrar em contato apresentando o show',
      'Enviar o material',
      'Fazer follow-up',
      'Negociar as condições',
      'Fechar a data',
      'Divulgar o show quando confirmado',
    ],
  },
  {
    id: '33',
    order: 13,
    category: 'Prospecção por tipo de contratante',
    title: 'Prospectar shows em festivais e produtores de eventos',
    tasks: [
      'Listar os festivais e produtores do seu nicho',
      'Marcar os prazos de inscrição e curadoria de cada um',
      'Preparar material de venda voltado para festivais',
      'Levantar os contatos dos produtores e curadores',
      'Inscrever-se nos festivais com chamada aberta',
      'Enviar material para os produtores',
      'Fazer follow-up',
      'Acompanhar os resultados das curadorias',
      'Negociar e confirmar as participações',
      'Registrar contatos para os próximos anos',
    ],
  },

  // ── 3.14 Empresariamento e suporte profissional ──────────────────────────────────────────────
  {
    id: '34',
    order: 14,
    category: 'Empresariamento e suporte profissional',
    title: 'Procurar empresário/a',
    tasks: [
      'Definir o que você espera de um empresário',
      'Listar empresários e escritórios que cuidam de artistas do seu porte',
      'Pesquisar a reputação e os artistas de cada um',
      'Preparar a apresentação do seu projeto e números',
      'Entrar em contato com os mais alinhados',
      'Marcar conversas para apresentar o projeto',
      'Avaliar a sintonia e a proposta de cada um',
      'Alinhar expectativas, percentual e responsabilidades',
      'Formalizar a parceria em contrato',
      'Definir a rotina de trabalho conjunta',
    ],
  },
  {
    id: '35',
    order: 14,
    category: 'Empresariamento e suporte profissional',
    title: 'Contratar assistente de produção / produtor executivo',
    tasks: [
      'Listar as tarefas que você precisa delegar',
      'Definir o perfil do profissional (assistente ou produtor executivo)',
      'Definir a carga horária e a forma de pagamento',
      'Divulgar a vaga ou pedir indicações',
      'Receber e selecionar candidatos',
      'Entrevistar os 3 melhores',
      'Escolher e fazer uma proposta',
      'Formalizar a contratação',
      'Treinar o profissional nos seus processos',
      'Definir as rotinas e os pontos de acompanhamento',
    ],
  },
  {
    id: '36',
    order: 14,
    category: 'Empresariamento e suporte profissional',
    title: 'Contratar suporte profissional especializado (BPO administrativo-financeiro, assessoria jurídica recorrente)',
    tasks: [
      'Listar as áreas que precisam de suporte (financeiro, jurídico)',
      'Definir o que vai terceirizar em cada área',
      'Pesquisar profissionais especializados em música ou cultura',
      'Pedir orçamento de 2 ou 3 de cada área',
      'Comparar serviços e valores',
      'Escolher e contratar',
      'Organizar e entregar os documentos necessários',
      'Definir a rotina de trabalho e os relatórios',
      'Acompanhar as entregas',
      'Revisar o serviço periodicamente',
    ],
  },

  // ── 3.15 Captação de recursos ────────────────────────────────────────────────────────────────
  {
    id: '37',
    order: 15,
    category: 'Captação de recursos',
    title: 'Pesquisar e inscrever o projeto em editais correspondentes, mantendo ativação contínua ao longo do ano',
    tasks: [
      'Listar os editais abertos compatíveis com o seu projeto',
      'Ler as regras de cada edital e marcar os prazos num calendário',
      'Reunir a documentação base (release, orçamento, contrapartidas)',
      'Avaliar se vai inscrever sozinho ou com profissional de captação',
      'Adaptar o projeto para o formato de cada edital escolhido',
      'Inscrever o projeto dentro do prazo',
      'Guardar o comprovante e a data do resultado',
      'Acompanhar o resultado de cada edital inscrito',
      'Criar um calendário fixo de editais recorrentes do ano',
      'Revisar o calendário de editais a cada 3 meses',
    ],
  },
  {
    id: '38',
    order: 15,
    category: 'Captação de recursos',
    title: 'Criar projeto incentivado (via lei de incentivo / Rouanet) para captação de patrocínio',
    tasks: [
      'Definir o conceito e o escopo do projeto incentivado',
      'Montar o orçamento do projeto',
      'Definir as contrapartidas (acessibilidade, sustentabilidade, etc.)',
      'Inscrever o projeto na lei de incentivo correspondente',
      'Acompanhar a aprovação do projeto',
      'Montar o material de venda do projeto para patrocinadores',
      'Listar 10 marcas com perfil de investimento alinhado',
      'Levantar o contato do setor de marketing de cada marca',
      'Apresentar o projeto para as marcas mapeadas',
      'Fazer follow-up e negociar o patrocínio',
    ],
  },
  {
    id: '39',
    order: 15,
    category: 'Captação de recursos',
    title: 'Criar campanha de financiamento coletivo (crowdfunding)',
    tasks: [
      'Definir o objetivo e a meta de arrecadação',
      'Calcular custos e o valor da meta',
      'Escolher a plataforma de crowdfunding',
      'Definir as recompensas por faixa de valor',
      'Produzir o vídeo e o texto da campanha',
      'Montar a página da campanha',
      'Criar um plano de divulgação',
      'Lançar a campanha',
      'Divulgar e atualizar durante a campanha',
      'Entregar as recompensas após o encerramento',
    ],
  },

  // ── 3.16 Patrocínio e marcas ─────────────────────────────────────────────────────────────────
  {
    id: '40',
    order: 16,
    category: 'Patrocínio e marcas',
    title: 'Mapear marcas alinhadas aos valores do artista, preparar material específico e prospectar ativações publicitárias / publis (avaliar parceria com profissional de ativação)',
    tasks: [
      'Definir o que você oferece a uma marca (contrapartidas)',
      'Listar marcas alinhadas aos seus valores e público',
      'Preparar um material de venda para marcas',
      'Levantar os contatos de marketing de cada marca',
      'Definir uma proposta de parceria para cada',
      'Entrar em contato apresentando a proposta',
      'Fazer follow-up',
      'Negociar os termos',
      'Fechar e formalizar a parceria',
      'Entregar as contrapartidas combinadas',
    ],
  },

  // ── 3.17 Influenciadores e creators ──────────────────────────────────────────────────────────
  {
    id: '41a',
    order: 17,
    category: 'Influenciadores e creators',
    title: 'Ativar influenciadores para divulgar o trabalho do artista (envio de media kit, parcerias remuneradas ou orgânicas)',
    tasks: [
      'Definir o público que você quer atingir',
      'Listar influenciadores que falam com esse público',
      'Ver o engajamento real de cada um',
      'Definir o formato da parceria (permuta, pago, orgânico)',
      'Preparar o material / media kit para enviar',
      'Entrar em contato com os influenciadores',
      'Combinar o conteúdo e a data',
      'Enviar o material',
      'Acompanhar a publicação',
      'Medir o resultado de cada ativação',
    ],
  },
  {
    id: '41b',
    order: 17,
    category: 'Influenciadores e creators',
    title: 'Prospectar oportunidades para o próprio artista atuar como influenciador junto a marcas (por conta própria ou em parceria com agência especializada)',
    tasks: [
      'Definir o seu nicho de conteúdo como creator',
      'Organizar suas redes para esse posicionamento',
      'Montar um media kit com seus números e público',
      'Definir sua tabela de valores por entregável',
      'Listar marcas que combinam com seu conteúdo',
      'Decidir se vai por conta própria ou via agência',
      'Se for via agência: pesquisar e fechar com uma',
      'Apresentar-se às marcas',
      'Negociar e fechar as primeiras publis',
      'Entregar o conteúdo e prestar contas dos resultados',
    ],
  },

  // ── 3.18 Feats e parcerias artísticas ────────────────────────────────────────────────────────
  {
    id: '42',
    order: 18,
    category: 'Feats e parcerias artísticas',
    title: 'Mapear artistas de interesse e ativar parcerias (feat, abertura de show, show em conjunto, turnê)',
    tasks: [
      'Listar artistas que combinam com o seu trabalho',
      'Priorizar por afinidade e alcance',
      'Levantar como chegar em cada um',
      'Definir o tipo de parceria (feat, abertura, show conjunto, turnê)',
      'Preparar uma proposta ou convite',
      'Entrar em contato apresentando a ideia',
      'Combinar os detalhes com quem topar',
      'Formalizar o combinado',
      'Realizar a parceria',
      'Divulgar em conjunto',
    ],
  },

  // ── 3.19 Lojinha e merchandising ─────────────────────────────────────────────────────────────
  {
    id: '43',
    order: 19,
    category: 'Lojinha e merchandising',
    title: 'Criar a "Lojinha do/da [nome]" (avaliar parcerias de licenciamento)',
    tasks: [
      'Definir os produtos que vai vender (camiseta, vinil, etc.)',
      'Pesquisar fornecedores ou parceiros de licenciamento',
      'Pedir orçamento e amostras',
      'Definir os preços de cada produto',
      'Escolher onde vender (loja online, nos shows)',
      'Criar a loja online ou o ponto de venda',
      'Produzir um estoque inicial',
      'Tirar fotos dos produtos',
      'Divulgar a lojinha nas redes e nos shows',
      'Controlar estoque e vendas',
    ],
  },

  // ── 3.20 Estrutura jurídica ──────────────────────────────────────────────────────────────────
  {
    id: '44',
    order: 20,
    category: 'Estrutura jurídica',
    title: 'Constituir empresa / migrar MEI para LTDA-EIRELI e formalizar contratos e memorando de entendimentos entre sócios',
    tasks: [
      'Consultar um contador sobre o melhor tipo de empresa',
      'Reunir a documentação necessária',
      'Abrir ou migrar a empresa (LTDA / EIRELI)',
      'Definir os CNAEs corretos para a atividade',
      'Se houver sócios: definir os termos da sociedade',
      'Redigir o contrato ou memorando entre sócios (com apoio jurídico)',
      'Assinar o contrato entre as partes',
      'Organizar as obrigações fiscais e contábeis',
      'Definir quem cuida da rotina administrativa',
      'Manter a documentação em dia',
    ],
  },

  // ── 3.21 Operacional e método de gestão ──────────────────────────────────────────────────────
  {
    id: '46',
    order: 21,
    category: 'Operacional e método de gestão',
    title: 'Contratar assistente executivo para acompanhamento do plano',
    tasks: [
      'Listar as tarefas de acompanhamento do plano',
      'Definir o perfil e a carga horária do assistente',
      'Definir a forma de pagamento',
      'Divulgar a vaga ou pedir indicações',
      'Entrevistar candidatos',
      'Escolher e contratar',
      'Apresentar o plano estratégico ao assistente',
      'Definir as rotinas de acompanhamento',
      'Criar um ritual de reunião semanal',
      'Acompanhar a execução do plano junto',
    ],
  },
  {
    id: '47',
    order: 21,
    category: 'Operacional e método de gestão',
    title: 'Adotar sistema de gestão de tarefas com agenda semanal de planejamento + acompanhamento (atas, plano de ação por estratégia)',
    tasks: [
      'Escolher uma ferramenta de gestão de tarefas',
      'Cadastrar todas as estratégias e tarefas na ferramenta',
      'Definir responsável e prazo de cada tarefa',
      'Definir o dia e horário da reunião semanal',
      'Criar um modelo de ata de reunião',
      'Fazer a primeira reunião de planejamento',
      'Atualizar o status das tarefas na ferramenta',
      'Registrar a ata de cada reunião',
      'Revisar o andamento toda semana',
      'Ajustar prazos e prioridades conforme necessário',
    ],
  },

  // ── 3.22 Pesquisa de mercado ─────────────────────────────────────────────────────────────────
  {
    id: '48',
    order: 22,
    category: 'Pesquisa de mercado',
    title: 'Fazer pesquisa de mercado (comportamento do consumidor + análise de concorrência)',
    tasks: [
      'Definir o que você quer descobrir com a pesquisa',
      'Definir quem você quer ouvir (público, contratantes)',
      'Decidir o método (formulário, entrevista, dados existentes)',
      'Montar as perguntas',
      'Aplicar a pesquisa',
      'Reunir as respostas',
      'Analisar os resultados',
      'Estudar os concorrentes e o mercado do nicho',
      'Tirar conclusões para o seu planejamento',
      'Ajustar suas estratégias com base nos achados',
    ],
  },

  // ── 3.23 Premiações e showcases ──────────────────────────────────────────────────────────────
  {
    id: '49',
    order: 23,
    category: 'Premiações e showcases',
    title: 'Inscrever o projeto em premiações pertinentes, pitchings, showcases e concursos do mercado',
    tasks: [
      'Listar as premiações, pitchings e concursos do seu segmento',
      'Marcar os prazos de inscrição de cada um',
      'Ver os critérios e o que cada um pede',
      'Selecionar os mais estratégicos',
      'Reunir o material exigido (música, vídeo, projeto)',
      'Inscrever-se dentro do prazo',
      'Guardar comprovantes e datas de resultado',
      'Acompanhar os resultados',
      'Divulgar conquistas e indicações',
      'Registrar para as próximas edições',
    ],
  },

  // ── 3.24 Mercado internacional ───────────────────────────────────────────────────────────────
  {
    id: '50',
    order: 24,
    category: 'Mercado internacional',
    title: 'Prospectar parcerias com bookers internacionais e planejar turnê internacional alinhada ao cronograma de lançamentos',
    tasks: [
      'Definir os países ou regiões de interesse',
      'Pesquisar bookers e agentes que atuam nesses lugares',
      'Preparar material de venda em inglês ou no idioma local',
      'Levantar os contatos dos bookers',
      'Apresentar seu trabalho e seus números',
      'Alinhar uma turnê com o cronograma de lançamentos',
      'Negociar as condições com o booker',
      'Fechar as datas',
      'Organizar a logística (visto, transporte, equipe)',
      'Realizar e registrar a turnê',
    ],
  },
  {
    id: '51',
    order: 24,
    category: 'Mercado internacional',
    title: 'Mapear festivais internacionais, editais de mobilidade e iniciativas de fomento internacionais',
    tasks: [
      'Pesquisar festivais internacionais do seu nicho',
      'Pesquisar editais de mobilidade e fomento internacional',
      'Marcar os prazos de cada um num calendário',
      'Ver os critérios e o que cada um exige',
      'Preparar o material em inglês',
      'Reunir a documentação necessária',
      'Inscrever-se nos festivais e editais',
      'Fazer follow-up quando possível',
      'Acompanhar os resultados',
      'Organizar a participação no que for aprovado',
    ],
  },
  {
    id: '52',
    order: 24,
    category: 'Mercado internacional',
    title: 'Contratar PR / assessoria de imprensa parceira no exterior',
    tasks: [
      'Definir o mercado ou país de foco',
      'Pesquisar profissionais de PR que atuam nesse mercado',
      'Pedir cases e orçamento',
      'Escolher e fechar com um',
      'Preparar o material de imprensa no idioma local',
      'Alinhar a estratégia e os objetivos com o PR',
      'Definir o período de trabalho (lançamento, turnê)',
      'Acompanhar a cobertura',
      'Registrar o clipping internacional',
      'Avaliar os resultados',
    ],
  },

  // ── 3.25 Eventos próprios e label ────────────────────────────────────────────────────────────
  {
    id: '53',
    order: 25,
    category: 'Eventos próprios e label',
    title: 'Criar evento/festival proprietário ou label, convidando outros artistas da cena',
    tasks: [
      'Definir o conceito do evento, festival ou label',
      'Definir o público e o formato',
      'Listar os artistas que quer convidar',
      'Montar o orçamento',
      'Definir o local e a data',
      'Buscar parceiros, patrocínio ou edital para viabilizar',
      'Convidar os artistas',
      'Produzir (estrutura, técnica, divulgação)',
      'Realizar o evento',
      'Avaliar os resultados e planejar a próxima edição',
    ],
  },

  // ── 3.26 Cursos, palestras e atividades complementares ───────────────────────────────────────
  {
    id: '54',
    order: 26,
    category: 'Cursos, palestras e atividades complementares',
    title: 'Lançar cursos, aulas ou mentorias como diversificação de receita',
    tasks: [
      'Definir o que você pode ensinar',
      'Definir o formato (presencial, online, gravado)',
      'Definir o público-alvo',
      'Estruturar o conteúdo do curso',
      'Definir o preço',
      'Escolher a plataforma (se online)',
      'Produzir o material do curso',
      'Criar uma página ou forma de inscrição',
      'Divulgar para sua base e redes',
      'Realizar a primeira turma e pedir feedback',
    ],
  },
  {
    id: '55',
    order: 26,
    category: 'Cursos, palestras e atividades complementares',
    title: 'Prospectar oportunidades como palestrante (por conta própria ou em parceria com agência especializada)',
    tasks: [
      'Definir os temas que você pode palestrar',
      'Montar uma apresentação ou material de palestra',
      'Definir seu valor por palestra',
      'Decidir se vai por conta própria ou via agência',
      'Se via agência: pesquisar e fechar com uma especializada',
      'Listar eventos, empresas e instituições potenciais',
      'Levantar os contatos',
      'Apresentar sua proposta de palestra',
      'Fazer follow-up',
      'Realizar as palestras confirmadas',
    ],
  },

  // ── 3.27 Estratégias adicionais ──────────────────────────────────────────────────────────────
  {
    id: 'N1',
    order: 27,
    category: 'Estratégias adicionais',
    title: 'Investir em formação técnica complementar (preparador vocal, coach técnico do instrumento, professor especializado)',
    tasks: [
      'Identificar o que você quer desenvolver (voz, instrumento, técnica)',
      'Pesquisar professores ou cursos especializados',
      'Ver referências e pedir valores',
      'Escolher o profissional ou curso',
      'Definir a frequência das aulas',
      'Montar uma rotina de estudo',
      'Fazer as aulas',
      'Praticar entre as aulas',
      'Avaliar a evolução periodicamente',
      'Aplicar o que aprendeu no trabalho',
    ],
  },
  {
    id: 'N2',
    order: 27,
    category: 'Estratégias adicionais',
    title: 'Estabelecer parcerias de composição com autores convidados para construir repertório autoral inédito',
    tasks: [
      'Definir o que você busca numa parceria de composição',
      'Listar compositores e autores que admira e que combinam',
      'Levantar como chegar em cada um',
      'Preparar uma ideia ou convite para a parceria',
      'Entrar em contato propondo compor junto',
      'Marcar as sessões de composição',
      'Compor as músicas em parceria',
      'Definir os direitos e a divisão de cada obra',
      'Registrar as obras com a divisão correta',
      'Planejar o lançamento das músicas',
    ],
  },
  {
    id: 'N3',
    order: 27,
    category: 'Estratégias adicionais',
    title: 'Contratar produtor musical experiente para os próximos lançamentos / pesquisar estúdio adequado ao projeto',
    tasks: [
      'Definir a referência sonora que você busca',
      'Pesquisar produtores que já fizeram esse tipo de som',
      'Ouvir trabalhos anteriores de cada um',
      'Pedir orçamento e disponibilidade dos 3 melhores',
      'Conversar sobre a visão do projeto',
      'Escolher o produtor e fechar',
      'Pesquisar e definir o estúdio de gravação',
      'Pré-produzir as músicas com o produtor',
      'Gravar',
      'Acompanhar mixagem e masterização',
    ],
  },
];

// Índice por id para lookup O(1).
export const STRATEGY_BY_ID: Record<string, BankStrategy> = STRATEGY_BANK.reduce(
  (acc, s) => {
    acc[s.id] = s;
    return acc;
  },
  {} as Record<string, BankStrategy>
);
